[package]
name = "data"
version = "0.0.1"
authors = ["Muhammad Abu Elula <Muhammad.abu-elula@whitesourcesoftware.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#time = "0.1.12"
log = '0.4'